services:
  # Service 1: The Firebase Emulators
  firebase-emulators:
    image: spine3/firebase-emulator
    environment:
      # Make sure it mateches later the one in app.js
      - GCP_PROJECT=your-firebase-project-id
    ports:
      - "4000:4000" # Emulator Suite UI
      - "8080:8080" # Firestore Emulator
      # Add other ports like 9099 for Auth later

  # Service 2: The simple Web App
  frontend:
    # Tells Docker to build the image from the Dockerfile in the ./webapp directory
    build: ./frontend
    ports:
      # Maps port 8000 on your local machine to port 80 inside the container
      - "8000:80"
    # This ensures the emulators are running before the webapp starts
    depends_on:
      - backend
  
  backend:
    build: ./backend
    ports:
      - "6969:6969"
    depends_on:
      - firebase-emulators