version: '3.8'

services:
  # Service 1: The Firebase Emulators
  firebase-emulators:
    image: spine3/firebase-emulator
    environment:
      # Make sure it mateches later the one in app.js
      - GCP_PROJECT=${GCP_PROJECT}
    ports:
      - "4000:4000" # Emulator Suite UI
      - "8080:8080" # Firestore Emulator
      - "9099:9099" # Auth Emulator
      # Add other ports like 9099 for Auth later
    volumes:
      - .:/webapp

  # Service 2: The frontend web app
  webapp:
    build: ./webapp
    ports:
      - "8000:5173"
    volumes:
      - ./webapp:/app
      # This named volume will store the node_modules directory
      # inside the container, completely separate from the host OS.
      - node_modules_volume:/app/node_modules
    env_file:
      - ./webapp/.env    
    environment:
      # This variable is required for the Vite dev server to work inside Docker
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - firebase-emulators
    command: npm run dev
  
  # Service 3: Backend
  backend:
    build: ./backend
    ports:
      - "6969:6969"
    env_file:
      - ./webapp/.env
    depends_on:
      - firebase-emulators

# Named volume for node_modules
volumes:
  node_modules_volume: