name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

# Cancel previous runs on the same branch/PR
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # -------------------- Backend unit tests --------------------
  backend-unit:
    name: Backend unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terrainapp/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: terrainapp/backend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Run unit tests (Jest)
        run: npm test -- --runInBand

  # -------------------- Webapp unit tests ---------------------
  webapp-unit:
    name: Webapp unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terrainapp/webapp
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: terrainapp/webapp/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Run unit tests (Jest / JSDOM)
        run: npm test -- --runInBand

  # -------------------- End-to-End (Playwright) ---------------
  e2e:
    name: E2E tests (Playwright)
    runs-on: ubuntu-latest
    needs: [backend-unit, webapp-unit]   # run after unit tests
    timeout-minutes: 30
    env:
      # common env used by your scripts
      GCP_PROJECT: demo-terrain
      FIRESTORE_EMULATOR_HOST: localhost:8080
      VITE_API_BASE_URL: http://localhost:6969/api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install backend deps (server will run from here)
      - name: Setup Node (backend) with cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: terrainapp/backend/package-lock.json
      - name: Install backend deps
        working-directory: terrainapp/backend
        run: npm ci

      # Install webapp deps (Vite dev server will run from here)
      - name: Setup Node (webapp) with cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: terrainapp/webapp/package-lock.json
      - name: Install webapp deps
        working-directory: terrainapp/webapp
        run: npm ci

      # Install e2e deps (Playwright + Firebase CLI + wait-on, etc.)
      - name: Setup Node (e2e) with cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: terrainapp/e2e/package-lock.json
      - name: Install e2e deps
        working-directory: terrainapp/e2e
        run: npm ci

      - name: Install Playwright browsers
        working-directory: terrainapp/e2e
        run: npm run install:browsers

      # Start services in background (keep them alive while tests run)
      - name: Start Firebase emulators (Auth + Firestore)
        working-directory: terrainapp/e2e
        run: |
          npx firebase emulators:start --only auth,firestore --project "$GCP_PROJECT" > emulators.log 2>&1 &
          echo $! > /tmp/pid-emulators

      - name: Wait for emulators
        working-directory: terrainapp/e2e
        run: npx wait-on tcp:8080 tcp:9099

      - name: Start backend API (port 6969)
        working-directory: terrainapp/e2e
        env:
          NODE_ENV: development
          GCP_PROJECT: ${{ env.GCP_PROJECT }}
          FIRESTORE_EMULATOR_HOST: ${{ env.FIRESTORE_EMULATOR_HOST }}
        run: |
          node ../backend/server.js > api.log 2>&1 &
          echo $! > /tmp/pid-api

      - name: Start webapp (Vite dev server on 5173)
        working-directory: terrainapp/e2e
        env:
          VITE_API_BASE_URL: ${{ env.VITE_API_BASE_URL }}
        run: |
          npm run dev --prefix ../webapp -- --host 0.0.0.0 --port 5173 > web.log 2>&1 &
          echo $! > /tmp/pid-web

      - name: Wait for API + Web to be ready
        working-directory: terrainapp/e2e
        run: npx wait-on http://localhost:6969/api/health http://localhost:5173/login

      - name: Seed Firestore + Auth
        working-directory: terrainapp/e2e
        run: |
          node ./seed-firestore.js
          # If you have auth seeding:
          if [ -f ./seed-auth.js ]; then node ./seed-auth.js; fi

      - name: Run Playwright E2E tests (single worker, headed-off)
        working-directory: terrainapp/e2e
        run: npx playwright test --workers=1

      # Upload Playwright HTML report if something fails
      - name: Upload Playwright report (artifact)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: terrainapp/e2e/playwright-report
          if-no-files-found: ignore

      # Always stop background processes so the job exits cleanly
      - name: Cleanup background services
        if: always()
        run: |
          for pidfile in /tmp/pid-emulators /tmp/pid-api /tmp/pid-web; do
            if [ -f "$pidfile" ]; then
              kill -TERM "$(cat "$pidfile")" || true
            fi
          done
          # Give them a moment to exit
          sleep 3