name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

# Cancel previous runs on same ref
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # -------------------- Backend unit tests --------------------
  backend-unit:
    name: Backend unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terrainapp/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: terrainapp/backend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Run unit tests (Jest)
        run: npm test -- --runInBand

  # -------------------- Webapp unit tests ---------------------
  webapp-unit:
    name: Webapp unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terrainapp/webapp
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: terrainapp/webapp/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Run unit tests (Jest / JSDOM)
        run: npm test -- --runInBand

  # -------------------- End-to-End (Playwright) ---------------
  e2e:
    name: E2E tests (Playwright)
    runs-on: ubuntu-latest
    needs: [backend-unit, webapp-unit]   # run after unit tests
    timeout-minutes: 30
    env:
      # Common env used by your scripts
      GCP_PROJECT: demo-terrain
      FIRESTORE_EMULATOR_HOST: 127.0.0.1:8080
      NODE_ENV: development
      VITE_API_BASE_URL: http://localhost:6969/api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Install backend deps ---
      - name: Setup Node (backend) with cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: terrainapp/backend/package-lock.json
      - name: Install backend deps
        working-directory: terrainapp/backend
        run: npm ci

      # --- Install webapp deps ---
      - name: Setup Node (webapp) with cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: terrainapp/webapp/package-lock.json
      - name: Install webapp deps
        working-directory: terrainapp/webapp
        run: npm ci

      # --- Install e2e deps ---
      - name: Setup Node (e2e) with cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: terrainapp/e2e/package-lock.json
      - name: Install e2e deps
        working-directory: terrainapp/e2e
        run: npm ci

      - name: Install Playwright browsers
        working-directory: terrainapp/e2e
        run: npx playwright install --with-deps chromium

      # --- Start services in background ---
      - name: Start Firebase emulators (Auth + Firestore)
        working-directory: terrainapp/e2e
        run: |
          npx firebase emulators:start --only auth,firestore --project "$GCP_PROJECT" > emulators.log 2>&1 &
          echo $! > /tmp/pid_emu

      - name: Wait for emulators
        run: npx wait-on tcp:8080 tcp:9099

      - name: Start backend API (port 6969)
        working-directory: terrainapp/backend
        env:
          NODE_ENV: ${{ env.NODE_ENV }}
          GCP_PROJECT: ${{ env.GCP_PROJECT }}
          FIRESTORE_EMULATOR_HOST: ${{ env.FIRESTORE_EMULATOR_HOST }}
        run: |
          nohup node server.js > ../../api.log 2>&1 &
          echo $! > /tmp/pid_api

      - name: Wait for backend health
        run: npx wait-on http://localhost:6969/api/health

      - name: Start webapp (Vite dev server on 5173)
        working-directory: terrainapp/webapp
        env:
          VITE_API_BASE_URL: ${{ env.VITE_API_BASE_URL }}
        run: |
          nohup npm run dev -- --host 0.0.0.0 --port 5173 > ../../web.log 2>&1 &
          echo $! > /tmp/pid_web

      - name: Wait for webapp
        run: npx wait-on http://localhost:5173/login

      # Seed data
      - name: Seed Firestore + Auth (optional)
        if: ${{ hashFiles('terrainapp/e2e/seed-firestore.js') != '' }}
        working-directory: terrainapp/e2e
        run: |
          node ./seed-firestore.js
          if [ -f ./seed-auth.js ]; then node ./seed-auth.js; fi

      # --- Run Playwright with CI-only config (no webServer block) ---
      - name: Run Playwright E2E (single worker)
        working-directory: terrainapp/e2e
        run: npx playwright test --config=playwright.ci.config.js --workers=1

      # --- Artifacts & logs on failure ---
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: terrainapp/e2e/playwright-report
          if-no-files-found: ignore

      - name: Upload logs (emulators/api/web)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: service-logs
          path: |
            terrainapp/e2e/emulators.log
            api.log
            web.log
          if-no-files-found: ignore

      # --- Teardown ---
      - name: Cleanup background services
        if: always()
        run: |
          for f in /tmp/pid_emu /tmp/pid_api /tmp/pid_web; do
            if [ -f "$f" ]; then kill -TERM "$(cat "$f")" || true; fi
          done
          sleep 2