name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - name: backend
            path: backend
            lock: backend/package-lock.json
          - name: frontend
            path: frontend
            lock: frontend/package-lock.json

    defaults:
      run:
        working-directory: ${{ matrix.pkg.path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug tree (paths & lockfiles)
        run: |
          echo "repo root:"
          ls -la
          echo "package dir:"
          ls -la .
          echo "lockfile? -> $LOCK"
        env:
          LOCK: ${{ matrix.pkg.lock }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ matrix.pkg.lock }}

      - name: Install
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "WARN: package-lock.json missing; using npm install (no cache key)."
            npm install
          fi

      - name: Run unit tests
        env:
          CI: true
          NODE_ENV: test
        run: npm test -- --ci --runInBand